"""create_links_table

Revision ID: 31e5cdfca963
Revises: e4e8b185ab55
Create Date: 2026-07-19 18:27:26.499312

"""
from typing import Sequence, Union

from alembic import op  # noqa: F401
import sqlalchemy as sa # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '31e5cdfca963'
down_revision: Union[str, Sequence[str], None] = 'e4e8b185ab55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
