"""remove_unique_constraint

Revision ID: 3343bce843cd
Revises: 1ea304e94f4c
Create Date: 2026-07-18 23:15:24.434279

"""
from typing import Sequence, Union
from alembic import op  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = '3343bce843cd'
down_revision: Union[str, Sequence[str], None] = '1ea304e94f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_code'), table_name='links')
    op.create_index(op.f('ix_links_code'), 'links', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_code'), table_name='links')
    op.create_index(op.f('ix_links_code'), 'links', ['code'], unique=1)
    # ### end Alembic commands ###
