"""restore_unique_constraint

Revision ID: e4e8b185ab55
Revises: 3343bce843cd
Create Date: 2026-07-18 23:17:05.344695

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = 'e4e8b185ab55'
down_revision: Union[str, Sequence[str], None] = '3343bce843cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_code'), table_name='links')
    op.create_index(op.f('ix_links_code'), 'links', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_code'), table_name='links')
    op.create_index(op.f('ix_links_code'), 'links', ['code'], unique=False)
    # ### end Alembic commands ###
